services:
  database:
    image: 'postgres:latest'
    container_name: 'taskifydb'
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    ports:
      - '5432:5432'
    volumes:
      - 'taskifydb:/var/lib/postgresql/data'
    secrets:
      - postgres_username
      - postgres_password
      - postgres_db
    
volumes:
  taskifydb:

secrets:
  postgres_username:
    file: postgres_username.txt
  postgres_password:
    file: postgres_password.txt
  postgres_db: 
    file: postgres_db.txt

# app:
#    build: .
#    command: >
#      sh -c "
#      npx prisma migrate deploy && 
#      npm run seed &&
#      npm run start"
#    depends_on:
#      - database
#    volumes:
#      - .:/app
#    ports:
#      - "3000:3000"
#    working_dir: /app