services:
  database:
    image: 'postgres:latest'
    container_name: 'taskifydb'
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}      
    ports:
      - '5432:5432'
    volumes:
      - 'taskifydb:/var/lib/postgresql/data'    
volumes:
  taskifydb: